### ISSUE TITLE
Debian/Ubuntu package update

### ISSUE THREAD

**Issue by steffengraber** [INCF/MUSIC#60]
Hi, are there any plans to upgrade the existing Debian/Ubuntu packages with version 1.0.7 to the current version 1.1.15?   
Sorry to ask this question here in the issues, but I haven't found another channel yet.

**Comment by mdjurfeldt** [comment]
Yes,

Are you dependent on this happening soon?

Best regards,
Mikael

**Comment by steffengraber** [comment]
I tried the Ubuntu packages together with the nest-simulator - no success. Only with the source code installation of Music (v1.1.15) I got further and was able to execute some simple examples.
We are in the process of providing Ubuntu packages of the nest-simulator over a ppa and it would be nice to be able to offer a package with a working dependency to Music.

Best

Steffen

**Comment by mdjurfeldt** [comment]
OK---give me a few days.

**Comment by steffengraber** [comment]
Perfect. Many thanks!

**Comment by steffengraber** [comment]
Hi @mdjurfeldt 
any news on that?

**Comment by mdjurfeldt** [comment]
Sorry for the delay---I'll do this tomorrow.

**Comment by mdjurfeldt** [comment]
This turned out to be more complicated than I expected since the new python bindings required some interaction between the music build system and then debian packaging system. But, I've now uploaded .deb packages for debian testing.

I've committed all changes to origin/master. My intent is that this will be part of the 1.1.16 release, but I will set the release tag first after the new packages have gone through the Debian system.

In principle, these should be buildable on any machine using HEAD and the following sequence:

./autogen.sh
./configure
make debian-source
cd ../music-1.1.16
apt-get build-dep music
dpkg-buildpackage -rfakeroot

Let me know if I can help you further.

Best regards,
Mikael

**Comment by mdjurfeldt** [comment]
MUSIC 1.1.16 is now released and accepted into Debian.

**Comment by steffengraber** [comment]
Many thanks!

**Comment by mdjurfeldt** [comment]
Please give feedback if there are problems. Now that the Debian-related work is done, I expect to be able to respond quicker. Closing ticket now.
