### ISSUE TITLE
configure ignore given PYTHON env var

### ISSUE THREAD

**Issue by EricDeveaud** [INCF/MUSIC#62]
Hello
while trying to install MUSIC in a virtual env using 

I noted that PYTHON value given to  configure is not honored.

see
```
./configure MPI_CXXFLAGS="-g -O3"  MPI_CFLAGS="-I$MPI_ROOT/include -pthread" MPI_LDFLAGS="-pthread -Wl,--enable-new-dtags -L$MPI_ROOT/lib -lmpi_cxx -lmpi" PYTHON=/opt/gensoft/exe/MUSIC/1.1.16/venv/bin/python
```
and 

```
[gensoft@38a8dee6f6d5 MUSIC-1.1.16]$ grep '^PYTHON =' Makefile
PYTHON = /opt/gensoft/adm/bin/python
```

I was expecting `PYTHON =/opt/gensoft/exe/MUSIC/1.1.16/venv/bin/python`

this makes `cd $(PYTHON} tests.py` to fail in pymusic/Makefile, more precisely in `pyconfig.pxi` rule

regards

Eric

**Comment by mdjurfeldt** [comment]
Dear Eric,

The way to specify to the configure script that a particular Python version should be used is using the option --with-python:

./configure --with-python=/my/bin/python

What probably happened in your case is that since this option was not given, it looked for a Python in your path.

I've updated README, mentioning this option, in commit b6a8787.

Please tell me if this helps.

**Comment by mdjurfeldt** [comment]
Dear Eric,

Just a reminder: Did this help with regard to your problem?  Can I close the issue?

Best regards,
Mikael

**Comment by EricDeveaud** [comment]
yes 
thanks
